In [1]:
import torch
import numpy
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])

In [6]:
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([[[7,8],
                     [9,10],
                       [11,12]]])
TENSOR

tensor([[[ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 2])

In [15]:
TENSOR[0]

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [16]:
random_tensor = torch.randn(3,4)

In [17]:
random_tensor

tensor([[ 0.3555, -0.6766, -0.7269, -1.1835],
        [ 2.0004, -2.1143,  0.0949, -0.8974],
        [-0.8327,  0.1024, -2.5880,  1.6983]])

In [18]:
random_image_size_tensor = torch.randn(size=(3,224,224))

In [19]:
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [20]:
zeros = torch.zeros(size=(4,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

In [24]:
one_to_ten = torch.arange(0,11,1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
torch.zeros_like(one_to_ten)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype = None,
                              device = None,
                              requires_grad = False)

In [27]:
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = torch.tensor([3.0,7.0,9.0],
                              dtype = torch.float16,
                              device = None,
                              requires_grad = False)

In [30]:
float_16_tensor

tensor([3., 7., 9.], dtype=torch.float16)

In [31]:
float_16_tensor.dtype

torch.float16

In [32]:
float_16_tensor_convert = float_32_tensor.type(torch.float16)

In [33]:
float_16_tensor_convert, float_16_tensor_convert.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [34]:
try1 = float_16_tensor*float_32_tensor
try1.dtype

torch.float32

In [35]:
random_tensor.T

tensor([[ 0.3555,  2.0004, -0.8327],
        [-0.6766, -2.1143,  0.1024],
        [-0.7269,  0.0949, -2.5880],
        [-1.1835, -0.8974,  1.6983]])

In [36]:
#finding min
x = torch.arange(0,101, 10)
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [37]:
x.max(), torch.max(x)

(tensor(100), tensor(100))

In [38]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(50.), tensor(50.))

In [39]:
torch.sum(x), x.sum()

(tensor(550), tensor(550))

In [40]:
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [41]:
x.argmax(), torch.argmax(x)

(tensor(10), tensor(10))

In [42]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [43]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [44]:
z = x.view(3,3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [45]:
#view is different from reshape, as view shares same memory as original, so any change in z,
#also changes the x

In [46]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked, x_stacked.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [47]:
x.shape

torch.Size([9])

In [48]:
x_squeezed = x.squeeze()

In [49]:
x_squeezed, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [50]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)

In [51]:
x_unsqueezed

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [52]:
x_original = torch.rand(size=(224,224,3))

In [53]:
x_original

tensor([[[0.6711, 0.7395, 0.3250],
         [0.4073, 0.0246, 0.6716],
         [0.6324, 0.1539, 0.0455],
         ...,
         [0.7265, 0.9418, 0.1106],
         [0.5756, 0.2119, 0.8202],
         [0.2528, 0.8151, 0.2524]],

        [[0.0543, 0.2033, 0.5599],
         [0.4208, 0.9069, 0.0891],
         [0.2690, 0.0255, 0.8273],
         ...,
         [0.4058, 0.7780, 0.1744],
         [0.0096, 0.5494, 0.9332],
         [0.8844, 0.2551, 0.8656]],

        [[0.8742, 0.2515, 0.9112],
         [0.0952, 0.4294, 0.6797],
         [0.0791, 0.1007, 0.7700],
         ...,
         [0.3639, 0.5380, 0.9558],
         [0.3513, 0.1516, 0.6633],
         [0.0116, 0.5697, 0.8830]],

        ...,

        [[0.8918, 0.2539, 0.0585],
         [0.6778, 0.9048, 0.1321],
         [0.0827, 0.3855, 0.4000],
         ...,
         [0.1159, 0.8734, 0.5074],
         [0.2404, 0.4989, 0.6956],
         [0.4346, 0.9122, 0.7816]],

        [[0.3846, 0.4668, 0.7853],
         [0.1349, 0.5663, 0.4540],
         [0.

In [54]:
x_permuted = x_original.permute(2,0,1)

In [55]:
x_permuted

tensor([[[0.6711, 0.4073, 0.6324,  ..., 0.7265, 0.5756, 0.2528],
         [0.0543, 0.4208, 0.2690,  ..., 0.4058, 0.0096, 0.8844],
         [0.8742, 0.0952, 0.0791,  ..., 0.3639, 0.3513, 0.0116],
         ...,
         [0.8918, 0.6778, 0.0827,  ..., 0.1159, 0.2404, 0.4346],
         [0.3846, 0.1349, 0.5166,  ..., 0.5185, 0.3062, 0.2615],
         [0.2538, 0.5169, 0.6905,  ..., 0.3177, 0.5433, 0.4240]],

        [[0.7395, 0.0246, 0.1539,  ..., 0.9418, 0.2119, 0.8151],
         [0.2033, 0.9069, 0.0255,  ..., 0.7780, 0.5494, 0.2551],
         [0.2515, 0.4294, 0.1007,  ..., 0.5380, 0.1516, 0.5697],
         ...,
         [0.2539, 0.9048, 0.3855,  ..., 0.8734, 0.4989, 0.9122],
         [0.4668, 0.5663, 0.1247,  ..., 0.9171, 0.3060, 0.3533],
         [0.7268, 0.1625, 0.5066,  ..., 0.8175, 0.1834, 0.0885]],

        [[0.3250, 0.6716, 0.0455,  ..., 0.1106, 0.8202, 0.2524],
         [0.5599, 0.0891, 0.8273,  ..., 0.1744, 0.9332, 0.8656],
         [0.9112, 0.6797, 0.7700,  ..., 0.9558, 0.6633, 0.

In [56]:
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [57]:
#permute is a view

In [58]:
##seeding in torch
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED) #this works for only one line on code after it, so if making many,
                                #tensors randomly, then write this manual_seed line again and again before it